### ISSUE TITLE
How to invoke Auth and ACL ?

### ISSUE THREAD

**Issue by s4kibs4mi** [emqtt/emq-elixir-plugin#13]

**Comment by terry-xiaoyu** [comment]
@s4kibs4mi Hi, this plugin is only a template for elixir, and no auth and acl for now. It would be great If you could write an auth/acl plugin based on this. 

You could check out the code of [emqx-auth-mysql](https://github.com/emqx/emqx-auth-mysql) for reference.

**Comment by s4kibs4mi** [comment]
@terry-xiaoyu, Created one @ https://github.com/ppeon/peon_mq
