### ISSUE TITLE
EMQx 4.3 compatibility

### ISSUE THREAD

**Issue by auror** [emqtt/emq-elixir-plugin#18]
Now that `emqx` started supporting Erlang/OTP 23 and the plugins becoming local apps. Would be better for a similar setup for Elixir based plugins

**Comment by 6293** [comment]
Hi. We are now discussing on how we support elixir plugins in v4.3.
https://github.com/emqx/eip/pull/16

**Comment by auror** [comment]
Cool @z8674558 That's great news. 

Elixir Plugin was indeed working ok with 4.2.x. But there were issues with transitive dependencies and the compilation order of the applications where the emqx's elixir plugin was getting compiled before the the dependencies of the plugin

**Comment by spokc** [comment]
cc: @zmstone

**Comment by auror** [comment]
cc: @zmstone
