### ISSUE TITLE
Cannot start plugin

### ISSUE THREAD

**Issue by lantica** [emqtt/emq-elixir-plugin#23]
I tried to follow the instruction in the readme, but error occurs when I start the plugin.

```
emqx ctl plugins start elixir_plugin_template-0.1.0
{
    "action": "ensure_started",
    "cause": {
        "app": "elixir_plugin_template",
        "err_app": "elixir_plugin_template",
        "error": "failed_to_start_plugin_app",
        "reason": "{bad_return,{{'Elixir.ElixirPluginTemplate.Application',start,[normal,[]]},{'EXIT',{undef,[{emqx,hook,['message.publish',{'Elixir.ElixirPluginTemplate',log_msg,[]}],[]},{'Elixir.ElixirPluginTemplate.Application',start,2,[{file,\"lib/elixir_plugin_template/application.ex\"},{line,20}]},{application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,293}]}]}}}}"
    },
    "name_vsn": "elixir_plugin_template-0.1.0",
    "result": "not_ok"
}
```

I am using the docker image `ghcr.io/emqx/emqx-builder/5.0-18:1.13.4-23.3.4.18-1-ubuntu20.04` to build the plugin and `emqx/emqx:5.0.19-elixir` to run the plugin.
It seems the `:emqx.hook` is undefined. Any suggestions?

**Comment by thalesmg** [comment]
Hi @lantica 

I have tried the following steps and had no problems.  Could you try the following to check if you also have problems?

1. Run:
```sh
docker \
    run -it \
    -p 38083:18083 \
    emqx/emqx:5.0.21-elixir 
```
2. Open `http://localhost:28083` and navigate to Extensions > Plugins, click "Install Plugin".
3. Download the plugin from the releases page (https://github.com/emqx/emqx-elixir-plugin/releases/tag/0.1.0-2) and upload it to the dashboard.
4. Click Install, and then Start.

**Comment by lantica** [comment]
Hi @thalesmg 
Thanks for your prompt response.
I've followed your instruction and give it a try with no luck.

In the dashboard, it shows a different error message.

<img width="883" alt="image" src="https://user-images.githubusercontent.com/46437192/227982537-99c7a20a-abd9-4950-90ac-1bdf7e321a92.png">

**Comment by lantica** [comment]
Btw it seems the release plugin can run normally with cli.
Do you have a recommendation for compile environment?

**Comment by lantica** [comment]
@thalesmg 

update:

I tried to compile from source with the source code in release v0.1.0-2 and the emqx50 branch.
It works only with the release v0.1.0-2 but not the emqx50 branch.
So there may be some issue in the recent commits.

**Comment by thalesmg** [comment]
>  Do you have a recommendation for compile environment?

We have some builder images we use in EMQX you can try to use.  For example: `docker run --rm -it -w /work -v $PWD:/work ghcr.io/emqx/emqx-builder/5.0-28:1.13.4-24.3.4.2-2-ubuntu20.04 bash`

Good catch, 0.1.0-2 has some updates that are needed for using more recent EMQX versions.  I'll merge them to `emqx50`.

**Comment by thalesmg** [comment]
There also seems to be some issue in the handling of uploaded that'll have to be fixed in the EMQX side as well for the dashboard to work properly :thinking:
